# Function

group of statement to perform a specific task

Why functions are not statement:
<br><br>
Reusability of code
Beause who just want to write same code again and again ? right so reuseability is the factor we use functions

How does a function works:
<br><br>
1.function definition<br>:-know what to do and how to do<br>
2.calling function<br>:-Repeat definition whenever needed<br>
3.return<br>:-Always get something when we call function<br>

def fn_name(arg):<br>
.......st1<br>
.......st2<br>
.......st3<br>
return


In [2]:
def hello():
    print("Hello world")

In [4]:
print(hello())

Hello world
None


In [7]:
#function can return(exit status)
#0-:zero error
#1:-minor error
#-1:-major error


In [1]:
#function can return also
def hello():
    return "Hello World"

In [8]:
#function can  also takes argument (info) to process
def hello(name):#formal arguments/parameters
    print("Hello world")
    print("Welcome user,",name)
    return True#Exit status

    

In [2]:
#msg = hello()
print(hello())

Hello World


In [9]:
print(hello("kirti"))

Hello world
Welcome user, kirti
True


In [10]:
if hello(input("Enter your name:")):
    print("Function successfully")
else:
    print("There is an error in function")

Enter your name:kirti
Hello world
Welcome user, kirti
Function successfully


In [8]:
import math
def prime(num):
    for i in range(2,round(math.sqrt(num)+1)):
        if num%i==0:
            return False
    return True

In [9]:
x=int(input("Enter a  number:"))
print(prime(x))

Enter a  number:23
True


In [10]:
def main():
    num = int(input("Enter a Number : "))
    if prime(num) :
        print("Given no. {} is a Prime Number ".format(num))
    else : 
        print("Given no. {} is not a Prime Number ".format(num
                                                          

SyntaxError: unexpected EOF while parsing (<ipython-input-10-3178a66c0f7a>, line 7)

In [11]:
main() 

Enter a Number : 23
Given no. 23 is a Prime Number 


In [13]:
def prime_range(start,end):
    for i in range(start,end+1):
        if prime(i):
            print(i,end=" ")
    print()

In [14]:
start=int(input("Enter starting range:"))
end=int(input("Enter ending range:"))
prime_range(start,end)

Enter starting range:1
Enter ending range:200
1 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199 


In [29]:
l=map(int,input("Enter a list").split(" "))
l1=list(l)
print(l1)

Enter a list1 2 3 4 5 6
[1, 2, 3, 4, 5, 6]


In [15]:
s = input("Type something")
k = s.split(',')
print(type(k))
print(k)


Type somethingkriti,priti,shruti,kirti,shubham
<class 'list'>
['kriti', 'priti', 'shruti', 'kirti', 'shubham']


In [16]:
def mymap(func,seq):
    r = []
    for var in seq : 
        k = func(var)
        r.append(k)
    return r

In [17]:
x = input("Float values as , seprated : ").split(',')
print("Before X = ",x)
x = mymap(float,x)
print("After X = ",x)

Float values as , seprated : 23.45,345,345.56
Before X =  ['23.45', '345', '345.56']
After X =  [23.45, 345.0, 345.56]


In [18]:
#Function Overloading

def area(r,b=0,c=0):
    if r and b and c :
        from math import sqrt
        s = ( r + b + c ) / 2
        A = sqrt(s*(s-r)*(s-b)*(s-c))
        return A
    elif r and b :
        return r*b
    else : 
        from math import pi 
        return r*r*pi

In [20]:
print(area(3))
print(area(3,5))
print(area(60,60,60))
print(prime(num=103424))

28.274333882308138
15
1558.8457268119896
False


In [22]:
def fun(a,b=0,c=0) :
    print("A = ",a)
    print("B = ",b)
    print("C = ",c)

In [23]:
fun(c=30,b=-20,a=22) #keywords arguments
fun(14,b=4)
fun(1,b=3,c=5)

A =  22
B =  -20
C =  30
A =  14
B =  4
C =  0
A =  1
B =  3
C =  5


In [24]:
def eve(*args):
    for var in args :
        if var % 2 == 0 : 
            print(var, end=', ')
    

In [25]:
eve(2,3,35,643,4,24,6,3,24,25,3,4,25,52,43,466,5)

2, 4, 24, 6, 24, 4, 52, 466, 

In [26]:
def main():
    eve(*map(int,input("Enter , seprated values : ").split(',')))
    if input("Press a key to continue : ") :
        main()

In [27]:
main()

Enter , seprated values : 1,2,3,4,5
2, 4, Press a key to continue : 1we4
Enter , seprated values : 1,2,3,4,5,6,6,7,8,9
2, 4, 6, 6, 8, Press a key to continue : 


In [28]:
def mydata(**kwargs):
    for key,value in kwargs.items() :
        print("{}={}".format(key,value))

In [29]:
mydata(name='python',version=3.6,scope='world wide')

name=python
version=3.6
scope=world wide


In [30]:
d  = { 
     '1':'one',
     '2':'two',
     '3':'three',
     '4':'four',
    }

In [31]:
mydata(**d)

1=one
2=two
3=three
4=four


In [33]:
def last_func(pos,key=10,*args,**kwargs):
    """I used to print all the arguments"""#doc-string
    print("Positional argument is : ",pos)
    print("Keyword Argument is : ",key)
    print("Here are your multiple arguments as tuple:")
    c = 0
    for value in args:
        c=c+1
        print("Args[{}] : {}".format(c,value))
    print("Here are your arguments as dctionary:")
    for key, value in kwargs.items():
        print("{}={}".format(key,value))
    print("Thanks for using this function")

In [34]:
print(last_func.__doc__)

I used to print all the arguments


In [35]:
last_func("Kirti",1,2,3,4,5,6,7,8,9,name='python',version='3',year='1991')

Positional argument is :  Kirti
Keyword Argument is :  1
Here are your multiple arguments as tuple:
Args[1] : 2
Args[2] : 3
Args[3] : 4
Args[4] : 5
Args[5] : 6
Args[6] : 7
Args[7] : 8
Args[8] : 9
Here are your arguments as dctionary:
name=python
version=3
year=1991
Thanks for using this function


In [36]:
del last_func

In [37]:
last_func

NameError: name 'last_func' is not defined

In [39]:
#global variable
x=5

In [40]:
x


5

In [41]:
def func():
    #If not defined externally it will give unbound local error
    global x
    x=x+5
    print(x)

In [42]:
func()

10


In [43]:
def func():
    x=5
    x=x**2
    print(x)

In [44]:
print(x)
func()
print(x)

10
25
10


In [46]:
#Global variable used in Reverse Process Call(RPC)
#Used for message passing

In [47]:
msg='I am global msg'

In [48]:
def fun1():
    print("Global : ",msg)

In [49]:
def fun2():
    global msg
    print("Previous msg : ",msg)
    msg=input("New msg : ")

In [50]:
fun1()
fun2()
fun1()

Global :  I am global msg
Previous msg :  I am global msg
New msg : i am boss
Global :  i am boss


In [51]:
def hello():
    print("Hello World")

In [52]:
#Recursion 

In [53]:
#in python,recursion stops after a certain item
##Since memory constraints are defined earlier if we want to change them we can do it externally


In [55]:
import sys
sys.getrecursionlimit()

2000

In [57]:
sys.setrecursionlimit(5000)

In [3]:
def hello():
    print("Hello World")
    if input("Press a key to continue:"):
        hello()
    
    

In [4]:
hello()

Hello World
Press a key to continue:drt
Hello World
Press a key to continue:efregt
Hello World
Press a key to continue:rgt
Hello World
Press a key to continue:ergthy
Hello World
Press a key to continue:fgh
Hello World
Press a key to continue:rtyt
Hello World
Press a key to continue:ddg
Hello World
Press a key to continue:


In [5]:
def fact(num):
    if num==1:
        return 1
    else:
        return num*fact(num-1)

In [6]:
fact(5)

120

In [3]:
c=1
def prime(num):
    global c
    c=c+1
    import math
    if c<=round(math.sqrt(num)):
        if num%c==0:
            return False
    else:
        return True
    return prime(num)
        

In [5]:
prime(int(input("Enter a number:")))

Enter a number:123


False

In [38]:
def nprime(num,c=2):
    if  num % c == 0 :
        return False
    if c <= round(sqrt(num)) :
        return nprime(num,c+1)
    return True

In [39]:
prime(23)

True

MAgic Fnctions in python<br>
lambda<br>
map<br>
filter <br>
reduce<br>


In [6]:
#Lambda :Anonymous Function(Inline function)

In [7]:
add =lambda x,y:x+y

In [9]:
add(2,3)

5

In [40]:
p = lambda x,p: x**p

In [41]:
p(7,3)

343

In [42]:
even_odd = lambda x : False if x % 2 else True

In [43]:
even_odd(3)

False

In [44]:
even_odd(146)

True

In [45]:
fact = lambda x: 1 if x == 1 else x*fact(x-1)

In [46]:
fact(5)

120

In [47]:
fact(12)

479001600

In [48]:
##Problem in recursion consumes a large amount of memory but very less time
##REcursion are similar to loops but recusion consumes more memory than loop and takes less time then loops


fact(123456)

RecursionError: maximum recursion depth exceeded in comparison

In [50]:
def fx(x,y):
    return x*y

In [70]:
x = [ 5.5,4.5,5.10,6,6.2,4.8,5.2,]
f = [ 10,15,20,3,5,25,30 ]


In [71]:
r = map(lambda x,y:x*y,x,f)

In [72]:
s_fx = sum(r)
s_f = sum(f)
mean = s_fx / s_f
print(mean)

5.087962962962963


In [73]:
import numpy as np


In [74]:
x = np.random.randint(45,85,50)

In [75]:
x

array([65, 81, 84, 50, 59, 66, 68, 50, 65, 66, 54, 80, 51, 46, 47, 84, 77,
       78, 50, 74, 74, 45, 59, 70, 51, 55, 47, 62, 82, 51, 77, 78, 60, 61,
       71, 53, 84, 66, 74, 54, 45, 63, 65, 48, 56, 50, 83, 81, 52, 80])

In [76]:
r = list(map(lambda x:True if x % 2 == 0 else False,x))

In [77]:
x

array([65, 81, 84, 50, 59, 66, 68, 50, 65, 66, 54, 80, 51, 46, 47, 84, 77,
       78, 50, 74, 74, 45, 59, 70, 51, 55, 47, 62, 82, 51, 77, 78, 60, 61,
       71, 53, 84, 66, 74, 54, 45, 63, 65, 48, 56, 50, 83, 81, 52, 80])

In [78]:
print(r)

[False, False, True, True, False, True, True, True, False, True, True, True, False, True, False, True, False, True, True, True, True, False, False, True, False, False, False, True, True, False, False, True, True, False, False, False, True, True, True, True, False, False, False, True, True, True, False, False, True, True]


In [79]:
r = list(filter(lambda x:True if x % 2 == 0 else False,x))

In [80]:
x

array([65, 81, 84, 50, 59, 66, 68, 50, 65, 66, 54, 80, 51, 46, 47, 84, 77,
       78, 50, 74, 74, 45, 59, 70, 51, 55, 47, 62, 82, 51, 77, 78, 60, 61,
       71, 53, 84, 66, 74, 54, 45, 63, 65, 48, 56, 50, 83, 81, 52, 80])

In [81]:
print(r)

[84, 50, 66, 68, 50, 66, 54, 80, 46, 84, 78, 50, 74, 74, 70, 62, 82, 78, 60, 84, 66, 74, 54, 48, 56, 50, 52, 80]


In [82]:
x

array([65, 81, 84, 50, 59, 66, 68, 50, 65, 66, 54, 80, 51, 46, 47, 84, 77,
       78, 50, 74, 74, 45, 59, 70, 51, 55, 47, 62, 82, 51, 77, 78, 60, 61,
       71, 53, 84, 66, 74, 54, 45, 63, 65, 48, 56, 50, 83, 81, 52, 80])

In [83]:
print(r)

[84, 50, 66, 68, 50, 66, 54, 80, 46, 84, 78, 50, 74, 74, 70, 62, 82, 78, 60, 84, 66, 74, 54, 48, 56, 50, 52, 80]


In [84]:
from functools import reduce

In [85]:
r = reduce(lambda x,y: x + y ,filter(prime,x))

In [86]:
r

480

In [87]:
sum(x)

3192

In [90]:
def fun(**kwargs):
    print(kwargs)
    print()

In [91]:
fun(x=5,name='python')

{'x': 5, 'name': 'python'}



In [92]:
fun(name='python',version=3.6,framwork=['Django','Flask','Web2py'])

{'name': 'python', 'version': 3.6, 'framwork': ['Django', 'Flask', 'Web2py']}



In [93]:
def fun(x,y=5,*args,**kwargs):
    print("Positional : ",x)
    print("Keyword / Default : ",y)
    print("Tuple Arguments : ",args)
    print("Dictionary Arguments : ",kwargs)

In [94]:
fun('hello')

Positional :  hello
Keyword / Default :  5
Tuple Arguments :  ()
Dictionary Arguments :  {}


In [95]:
fun('hello','bye',1,2,3,45,6,name='something',hello='hey bhagwaan')

Positional :  hello
Keyword / Default :  bye
Tuple Arguments :  (1, 2, 3, 45, 6)
Dictionary Arguments :  {'name': 'something', 'hello': 'hey bhagwaan'}


In [96]:
k = [ '1','2','3','4','5']

In [97]:
r = []
for value in k :
    x = int(value)
    r.append(x)

In [98]:
r

[1, 2, 3, 4, 5]

In [99]:
k

['1', '2', '3', '4', '5']

In [100]:
r = list(map(int,k))
r

[1, 2, 3, 4, 5]

In [103]:
x = input()

1 2 3 4 5


In [104]:
x

'1 2 3 4 5'

In [105]:
y=x.split()

In [106]:
y

['1', '2', '3', '4', '5']

In [107]:
z = list(map(int,y))

In [108]:
z

[1, 2, 3, 4, 5]

In [109]:
x = list(map(int,input().split(',')))
x

1,2,3,4,5,6,7,8,9


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [110]:
x = [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
x.__sizeof__()

248

In [111]:
y = range(1,27)
y.__sizeof__()

48

In [112]:
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]


In [113]:
y = iter(y)

In [114]:
eve_odd = lambda num : True if num % 2 == 0 else False

In [115]:
eve_odd(12)

True

In [116]:
k = list(map(eve_odd,x))

In [117]:
print(k)
print(x)

[False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]


In [118]:
r = list(filter(eve_odd,x))
print(r)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]


In [119]:
from functools import reduce

In [120]:
p = reduce(lambda m,n:m+n,x)
p

351